import "~/styles/globals.css";

import { type Metadata } from "next";
import { Darumadrop_One, Fredoka } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
});

const darumadropOne = Darumadrop_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-funky",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${darumadropOne.variable} ${fredoka.variable}`}>
      <body className="bg-background">{children}</body>
    </html>
  );
}
